<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'5Z+56K6t6YCa55+l');
$cfg_Cs[3]=array(0,1,1,'5Zyo57q/5oql5ZCN');
$cfg_Cs[4]=array(0,1,1,'6K++56iL55uu5b2V');
$cfg_Cs[5]=array(0,1,1,'5Z+56K6t6LWE5rqQ');
$cfg_Cs[6]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[7]=array(4,1,1,'572R57uc5Z+656GA5pyN5Yqh');
$cfg_Cs[8]=array(4,1,1,'5L+h5oGv5bqU55So57O757uf');
$cfg_Cs[11]=array(0,1,1,'6aaW6aG1YmFubmVy');
$cfg_Cs[12]=array(0,1,1,'6aaW6aG15Z+56K6t5YWs5ZGK');
?>