<?php
$z[0]=Array("global","",227,252);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",1035,1060);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",1142,1167);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1245,1270);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1311,1337);
$z[4][4]['name']="cfg_dataurl";
$z[5]=Array("global","",1493,1520);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1613,1640);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",1643,1669);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1812,1839);
$z[8][4]['name']="cfg_basehost";
$z[9]=Array("global","",1859,1891);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1940,1966);
$z[10][4]['name']="cfg_webname";
$z[11]=Array("global","",2299,2324);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("channel","\r\n          <li>\r\n            <a href='[field:typeurl/]' [field:rel/]>\r\n              <span>[field:typename/]</span>\r\n            </a>\r\n          </li>\r\n          ",2409,2794);
$z[12][4]['type']="top";
$z[12][4]['row']="10";
$z[12][4]['currentstyle']="<li class='hover'> <a href='~typelink~' ~rel~> <span>~typename~</span> </a> </li>";
$z[13]=Array("global","",2897,2922);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("tag","\r\n            <li>\r\n              <a href='[field:link/]'>[field:tag /]</a>\r\n            </li>\r\n            ",3742,3904);
$z[14][4]['row']="10";
$z[14][4]['getall']="1";
$z[14][4]['sort']="month";

?>